# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  solution: 'CFB.sln'
  buildPlatform: 'x86|x64'
  buildConfiguration: 'Release|Debug'
  appxPackageDir: '$(build.artifactStagingDirectory)\AppxPackages\\'
  WdkInstallScriptUrl: 'https://gist.githubusercontent.com/hugsy/eb46d4f776d35ed00418c3d47051c9b0/raw/Install-WDK.ps1'
  
jobs:
- job: 'Build_Broker_Windows64'
  pool:
#    vmImage: 'windows-2019'
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: (New-Object Net.WebClient).Proxy.Credentials=[Net.CredentialCache]::DefaultNetworkCredentials;iwr($env:URL)|iex
    env:
      URL: $(WdkInstallScriptUrl)
    displayName: 'Download and Install WDK10'
  - task: MSBuild@1
    displayName: 'Build Broker 64-bit'
    inputs: 
      msbuildArguments: '-nologo /m /p:Configuration=Release'
      solution: CFB.sln
  - task: PublishBuildArtifacts@1
    condition: ne(variables['Build.Reason'], 'PullRequest')
    inputs:
      pathtoPublish: './build'
      artifactName: win64build
