#
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
#

trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'windows-latest'


variables:
  solution: '**/*.sln'
  buildPlatform: 'x86|x64'
  buildConfiguration: 'Release'


steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@Common
  inputs:
    solution: '$(solution)'
    projectFile: '**/Common.vcxproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@Driver
  inputs:
    solution: '$(solution)'
    projectFile: '**/Driver.vcxproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSBuild@Broker
  inputs:
    solution: '$(solution)'
    projectFile: '**/Broker.vcxproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: VSBuild@GUI
  inputs:
    solution: '$(solution)'
    projectFile: '**/GUI.vcxproj'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
